### ISSUE TITLE
test failure annotations marks test logs as failures

### ISSUE THREAD

**Issue by capnspacehook** [WillAbides/setup-go-faster#27]
I think annotating test failures is a really good idea, however I noticed that calls to `testing.(T).Log` and friends match the test failure annotation regex.

Here's an example of this happening (at the very bottom): https://github.com/capnspacehook/egress-eddie/pull/61/files

**Comment by WillAbides** [comment]
Thank you for reporting this. I'll work on fixing this today.

**Comment by WillAbides** [comment]
v1.12.0 reverts to the old behavior unless you set `annotate-test-logs: true`.
