### ISSUE TITLE
Add in "stable" and "oldstable"

### ISSUE THREAD

**Issue by Jacalz** [WillAbides/setup-go-faster#31]
> Just the stable input. I don't understand what stable adds for actions/setup-go. If you only want stable builds you can set go-version accordingly. If there is good use case for stable, it can be added.

The README mentions that `stable` hasn't been added. I believe it would be very good to add it because it means that the workflow file can be the same without having to create a new commit (plus PR depending on the project). The same goes for using `oldstable` for the older maintained release. Using these two makes it possible to basically have a fire-and-forget workflow that constantly keeps updated to test with the latest supported Go versions.

This goes hand in hand with my issue over at setup-go: https://github.com/actions/setup-go/issues/450

**Comment by WillAbides** [comment]
Thanks for bringing this up. You can already simulate `stable` by setting `go-version: 1.x`, but I don't think there is a way to simulate `oldstable`. Your use case seems valid, and there doesn't seem to be a downside, so I'm inclined to add this. I'll be looking at it today, but I can't be sure when a PR will land.

As an aside, the part of the README you quoted is referencing the "stable" input as it existed in `actions/setup-go@v2`. v3 dropped that input and replaced it with the `stable` and `oldstable` aliases.

**Comment by WillAbides** [comment]
This is released in [v1.14.0](https://github.com/WillAbides/setup-go-faster/releases/tag/v1.14.0)

**Comment by Jacalz** [comment]
Thanks :)
